baseURL = 'https://blackestwhite.github.io/'
title = 'My New Hugo Site'
theme = 'ez'
publishDir = 'public'
DefaultContentLanguage = "en"
enableemoji = true
[markup.goldmark.renderer]
hardWraps = true
[languages]
    [languages.en]
        contentDir = "content/en"
        languageName = "Enlgish"
        [languages.en.params]
            linkedin = "https://blackestwhite.github.io/en/"
    [languages.fa]
        contentDir = "content/fa"
        languageName = "Persian"
        [languages.fa.params]
            linkedin = "https://blackestwhite.github.io/fa/"